//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int Note_id { get; set; }
        public string Note_title { get; set; }
        public string Note_text { get; set; }
        public string Note_tag { get; set; }
        public Nullable<int> Note_priority { get; set; }
        public Nullable<System.DateTime> Note_date { get; set; }
        public Nullable<System.DateTime> Note_edit_date { get; set; }
    }
}
